name: Deploy Asset Predict Web to EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy nginx config to EC2
        run: |
          scp -o StrictHostKeyChecking=no ./src/asset-predict-web-nginx.conf ec2-user@${{ secrets.EC2_HOST }}:/tmp/

      - name: Copy deploy script to EC2
        run: |
          scp -o StrictHostKeyChecking=no ./src/deploy_asset_predict_web.sh ec2-user@${{ secrets.EC2_HOST }}:/tmp/

      - name: Run deploy script on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} \
            "sudo bash /tmp/deploy_asset_predict_web.sh"

# Required secrets:
# - EC2_SSH_KEY: Private SSH key for ec2-user
# - EC2_HOST: Public IP or DNS of the EC2 instance
